/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diegomolina_lab7;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crear = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        bt_crear = new javax.swing.JButton();
        jd_modificar = new javax.swing.JDialog();
        cb_equiposMod = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreMod = new javax.swing.JTextField();
        bt_modificar = new javax.swing.JButton();
        jd_eliminar = new javax.swing.JDialog();
        bt_eliminar = new javax.swing.JButton();
        cb_equiposElim = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jd_simular = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_equipo1 = new javax.swing.JComboBox<>();
        cb_equipo2 = new javax.swing.JComboBox<>();
        jl_num1 = new javax.swing.JLabel();
        jl_num2 = new javax.swing.JLabel();
        bt_simular = new javax.swing.JButton();
        jd_tabla = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_crear = new javax.swing.JMenuItem();
        mi_modificar = new javax.swing.JMenuItem();
        mi_eliminar = new javax.swing.JMenuItem();
        mi_cargar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_simular = new javax.swing.JMenuItem();
        mi_tabla = new javax.swing.JMenuItem();

        jd_crear.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Creacion de Equipo");

        jLabel2.setText("Nombre del Equipo");

        bt_crear.setText("Crear Equipo");
        bt_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearLayout = new javax.swing.GroupLayout(jd_crear.getContentPane());
        jd_crear.getContentPane().setLayout(jd_crearLayout);
        jd_crearLayout.setHorizontalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(jd_crearLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jd_crearLayout.setVerticalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jd_modificar.setSize(new java.awt.Dimension(400, 300));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Modificar Equipo");

        jLabel4.setText("Seleccione un equipo");

        jLabel5.setText("Ingrese el Nuevo Nombre");

        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarLayout = new javax.swing.GroupLayout(jd_modificar.getContentPane());
        jd_modificar.getContentPane().setLayout(jd_modificarLayout);
        jd_modificarLayout.setHorizontalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(cb_equiposMod, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(tf_nombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jd_modificarLayout.setVerticalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_equiposMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jd_eliminar.setSize(new java.awt.Dimension(400, 300));

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Eliminar Equipo");

        jLabel8.setText("Seleccione un equipo");

        javax.swing.GroupLayout jd_eliminarLayout = new javax.swing.GroupLayout(jd_eliminar.getContentPane());
        jd_eliminar.getContentPane().setLayout(jd_eliminarLayout);
        jd_eliminarLayout.setHorizontalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(cb_equiposElim, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_eliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jd_eliminarLayout.setVerticalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_equiposElim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jd_simular.setSize(new java.awt.Dimension(400, 300));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Simular");

        jLabel9.setText("Escoga los dos equipos que jugaran");

        bt_simular.setText("Simular");
        bt_simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_simularLayout = new javax.swing.GroupLayout(jd_simular.getContentPane());
        jd_simular.getContentPane().setLayout(jd_simularLayout);
        jd_simularLayout.setHorizontalGroup(
            jd_simularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simularLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simularLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_simularLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(bt_simular, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_simularLayout.createSequentialGroup()
                .addGroup(jd_simularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simularLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simularLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jl_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jd_simularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simularLayout.createSequentialGroup()
                        .addComponent(cb_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simularLayout.createSequentialGroup()
                        .addComponent(jl_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jd_simularLayout.setVerticalGroup(
            jd_simularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simularLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_simularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_simularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(bt_simular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout jd_tablaLayout = new javax.swing.GroupLayout(jd_tabla.getContentPane());
        jd_tabla.getContentPane().setLayout(jd_tablaLayout);
        jd_tablaLayout.setHorizontalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_tablaLayout.setVerticalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Equipos");

        mi_crear.setText("Crear Equipo");
        mi_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_crearActionPerformed(evt);
            }
        });
        jMenu1.add(mi_crear);

        mi_modificar.setText("Modificar Equipo");
        mi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarActionPerformed(evt);
            }
        });
        jMenu1.add(mi_modificar);

        mi_eliminar.setText("Eliminar Equipo");
        mi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_eliminarActionPerformed(evt);
            }
        });
        jMenu1.add(mi_eliminar);

        mi_cargar.setText("Cargar Archivo");
        mi_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cargarActionPerformed(evt);
            }
        });
        jMenu1.add(mi_cargar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Partidos");

        mi_simular.setText("Simular");
        mi_simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_simularActionPerformed(evt);
            }
        });
        jMenu2.add(mi_simular);

        mi_tabla.setText("Tabla");
        mi_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_tablaActionPerformed(evt);
            }
        });
        jMenu2.add(mi_tabla);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_crearActionPerformed
        // TODO add your handling code here:
        jd_crear.setVisible(true);
        jd_crear.setLocationRelativeTo(this);
    }//GEN-LAST:event_mi_crearActionPerformed

    private void mi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarActionPerformed
        // TODO add your handling code here:
        if(equipos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe de agregar equipos para poder modificarlos");
        }
        else{
            jd_modificar.setVisible(true);
            jd_modificar.setLocationRelativeTo(this);
            DefaultComboBoxModel dc=
            (DefaultComboBoxModel) cb_equiposMod.getModel();
            dc.removeAllElements();
            for (Equipo e : equipos) {
                dc.addElement(e);
            }
        }
    }//GEN-LAST:event_mi_modificarActionPerformed

    private void mi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_eliminarActionPerformed
        // TODO add your handling code here:
        if(equipos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe de agregar equipos para poder eliminarlos");
        }
        else{
            jd_eliminar.setVisible(true);
            jd_eliminar.setLocationRelativeTo(this);
            DefaultComboBoxModel dc=
            (DefaultComboBoxModel) cb_equiposElim.getModel();
            dc.removeAllElements();
            for (Equipo e : equipos) {
                dc.addElement(e);
            }
        }
    }//GEN-LAST:event_mi_eliminarActionPerformed

    private void mi_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_cargarActionPerformed

    private void mi_simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_simularActionPerformed
        // TODO add your handling code here:
        if(equipos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe de agregar equipos para poder simular partidos");
        }
        else{
            jd_simular.setVisible(true);
            jd_simular.setLocationRelativeTo(this);
            DefaultComboBoxModel dc=
            (DefaultComboBoxModel) cb_equipo1.getModel();
            DefaultComboBoxModel dc2=
            (DefaultComboBoxModel) cb_equipo2.getModel();
            dc.removeAllElements();
            dc2.removeAllElements();
            for (Equipo e : equipos) {
                dc.addElement(e);
            }
            for (Equipo e : equipos) {
                dc2.addElement(e);
            }
        }
        
    }//GEN-LAST:event_mi_simularActionPerformed

    private void mi_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_tablaActionPerformed
        // TODO add your handling code here:
        if(equipos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe de agregar equipos para poder listarlos");
        }
        else{
           jd_tabla.setVisible(true);
            jd_tabla.setLocationRelativeTo(this); 
        }
        
    }//GEN-LAST:event_mi_tablaActionPerformed

    private void bt_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearActionPerformed
        // TODO add your handling code here:
        String nombre;
        nombre = tf_nombre.getText();
        Equipo e = new Equipo(nombre, 0, 0, 0, 0, 0, 0, 0);
        equipos.add(e);
        JOptionPane.showMessageDialog(null, "Se ha agregado exitosamente el equipo");
        jd_crear.setVisible(false);
        tf_nombre.setText("");
        try {
            aE.escribirArchivo(equipos);
        } catch (IOException ex) {
            System.out.println("Ha ocurrido un grave error");
        }
    }//GEN-LAST:event_bt_crearActionPerformed

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        // TODO add your handling code here:
        int pos = cb_equiposMod.getSelectedIndex();
        String nombre = tf_nombreMod.getText();
        equipos.get(pos).setNombre(nombre);
        JOptionPane.showMessageDialog(null, "Se ha modificado exitosamente el equipo");
        jd_modificar.setVisible(false);
        tf_nombreMod.setText("");
        try {
            aE.escribirArchivo(equipos);
        } catch (IOException ex) {
            System.out.println("Ha ocurrido un grave error");
        }
        
    }//GEN-LAST:event_bt_modificarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        // TODO add your handling code here:
            int pos = cb_equiposElim.getSelectedIndex();
            equipos.remove(pos);
            JOptionPane.showMessageDialog(null, "Se ha eliminado exitosamente el equipo");
            jd_eliminar.setVisible(false);
        try {
            aE.escribirArchivo(equipos);
        } catch (IOException ex) {
            System.out.println("Ha ocurrido un grave error");
        }
        
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simularActionPerformed
        // TODO add your handling code here:
        int x = 0+r.nextInt(6);
        int y = 0+r.nextInt(6);
        jl_num1.setText(x+"");
        jl_num2.setText(y+"");
    }//GEN-LAST:event_bt_simularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_simular;
    private javax.swing.JComboBox<String> cb_equipo1;
    private javax.swing.JComboBox<String> cb_equipo2;
    private javax.swing.JComboBox<String> cb_equiposElim;
    private javax.swing.JComboBox<String> cb_equiposMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_eliminar;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JDialog jd_simular;
    private javax.swing.JDialog jd_tabla;
    private javax.swing.JLabel jl_num1;
    private javax.swing.JLabel jl_num2;
    private javax.swing.JMenuItem mi_cargar;
    private javax.swing.JMenuItem mi_crear;
    private javax.swing.JMenuItem mi_eliminar;
    private javax.swing.JMenuItem mi_modificar;
    private javax.swing.JMenuItem mi_simular;
    private javax.swing.JMenuItem mi_tabla;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreMod;
    // End of variables declaration//GEN-END:variables
    ArrayList<Equipo> equipos = new ArrayList();
    administrarEquipo aE = new administrarEquipo("./Equipos.txt");
    Random r = new Random();
}
